# docker-compose.yml
version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vite_frontend
    restart: unless-stopped
    ports:
      - "4202:80"
    networks:
      - frontend_network

networks:
  frontend_network:
    driver: bridge